name: Deploy Dev

on:
  push:
    branches:
      - develop
    repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: npm intall 
      run: npm install
    - name: npm build
      env:
        NODE_ENV: development
      run: npm run build
    - name: Deploy to GH Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: gh-pages
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_KEY }}